visualize: 1
world_name: rosebv

perception:
    fit_shapes: 1
    model_list: all_models.yml

plugins:
- name: gui_server
  lib: libed_gui_server_plugin.so
  parameters:
      robot_name: rose
- name: navigation
  lib: libed_navigation_plugin.so
  parameters:
      occupancy_grid_publisher:
          resolution: 0.05
          frame_id: /map
          min_z: 0.05
          max_z: 1.8
- name: tf_publisher
  lib: libed_tf_publisher_plugin.so
  parameters:
      root_frame_id: /map
- name: robot_plugin
  lib: libed_robot_plugin.so
  parameters:
      robot_name: rose
      urdf_rosparam: /rose/robot_description
      joint_topics:
        - topic: /joint_states
- name: kinect_integration
  lib: libed_kinect_plugin.so
  parameters:
      topic: /camera/rgbd
      voxel_size: 0.02
      max_range: 2.0
      clearing_padding_fraction: 0.05
      normal_k_search: 15
      visualize: 0
      association_modules:
        - type: PointNormal
          parameters:
              association_correspondence_distance: 0.3
              position_weight: 2.0
              normal_weight: 1.0
              render_width: 320
              render_max_range: 2.2
              render_voxel_size: 0.02
              normal_k_search: 15
              visualize: 0
        - type: PolygonHeight
          parameters:
              max_range: 2.0
              tolerance: 0.035
              min_cluster_size: 20
              visualize: 0
      segmentation_modules:
      - type: EuclideanClustering
        parameters:
            tolerance: 0.035
            min_cluster_size: 20
            visualize: 0
